name: Build Docker
on:
  workflow_dispatch:
  schedule:
    - cron:  "0 4 * * *"
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  generate:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/gwmcelfresh/napari-stitch
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

     # - name: Set up Docker Buildx
     #   uses: docker/setup-buildx-action@v2.2.1
        #with:
          # Use the previous version of buildx to force docker to save a V1 image,
          # since Exacloud's outdated docker version cannot handle V2/OCI:
         # version: v0.9.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/gwmcelfresh/napari-stitch:latest
            ghcr.io/gwmcelfresh/napari-stitch:nightly
